name: Server Code Quality Check

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]
    paths:
      - 'server/**'

defaults:
  run:
    working-directory: server

jobs:
  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Run Checkstyle
        run: ./mvnw checkstyle:checkstyle
      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: checkstyle-report-${{ github.sha }}
          path: server/target/checkstyle-result.xml
          retention-days: 7
      - name: Run SpotBugs
        run: ./mvnw com.github.spotbugs:spotbugs-maven-plugin:spotbugs
      - name: Upload SpotBugs report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: spotbugs-report-${{ github.sha }}
          path: server/target/spotbugsXml.xml
          retention-days: 7
      - name: Run PMD
        run: ./mvnw pmd:pmd
      - name: Upload PMD report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pmd-report-${{ github.sha }}
          path: server/target/pmd.xml
          retention-days: 7
      - name: Generate code quality summary
        run: |
          echo "## Code Quality Report" >> $GITHUB_STEP_SUMMARY
          echo "- Checkstyle, SpotBugs, and PMD analysis completed." >> $GITHUB_STEP_SUMMARY 